import { Manrope } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const manrope = Manrope({
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "MoneyVision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${manrope.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
